[workspace]
members = [
    "verilator",
    "language-support/verilog",
    "language-support/verilog-macro",
    "language-support/verilog-macro-builder",
    "language-support/spade",
    "language-support/spade-macro",
    "examples/verilog-project",
    "examples/spade-project",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
authors = ["Ethan Uppal"]
edition = "2021"
rust-version = "1.83"
description = "🦀 No nonsense hardware testing in Rust 🛠️"
repository = "https://github.com/ethanuppal/dumbname"
readme = "README.md"
license = "MPL-2.0"

[workspace.dependencies]
snafu = "0.8.5"
camino = "1.1.9"
libc = "0.2.169"
libloading = "0.8.6"
proc-macro2 = "1.0.93"
syn = { version = "2.0.96", features = ["full"] }
quote = "1.0.38"
sv-parser = "0.13.3"
spade-parser = "0.12.1"
spade-ast = "0.12.1"
log = "0.4.25"
colog = "1.3.0"

verilator = { path = "verilator" }
verilog = { path = "language-support/verilog" }
spade = { path = "language-support/spade" }
