[workspace]
members = [
    "verilator",
    "spade-support/spade",
    "spade-support/spade-macro",
    "spade-support/example-project/test",
    "verilog-support/verilog",
    "verilog-support/verilog-macro",
    "verilog-support/verilog-macro-builder",
    "verilog-support/example-project",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
authors = ["Ethan Uppal"]
edition = "2021"
rust-version = "1.83"
description = "🦀 No nonsense hardware testing in Rust 🛠️"
repository = "https://github.com/ethanuppal/dumbname"
readme = "README.md"
license = "MPL-2.0"

[workspace.dependencies]
snafu = "0.8.5"
camino = "1.1.9"
libc = "0.2.169"
libloading = "0.8.6"
proc-macro2 = "1.0.93"
syn = { version = "2.0.96", features = ["full"] }
quote = "1.0.38"
sv-parser = "0.13.3"
spade-parser = { git = "https://gitlab.com/ethanuppal/spade", rev = "ba4de0855d1d869805f98de05e0f4ad8f7441339" } #, rev = "0c96a2248fe80b550430be86d3efc1dc9cd15c6f" }
spade-ast = { git = "https://gitlab.com/ethanuppal/spade", rev = "ba4de0855d1d869805f98de05e0f4ad8f7441339" }    #, rev = "0c96a2248fe80b550430be86d3efc1dc9cd15c6f" }
log = "0.4.25"
colog = "1.3.0"

verilator = { path = "verilator" }
verilog = { path = "verilog-support/verilog" }
spade = { path = "spade-support/spade" }
