[package]
name = "verilog-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
verilog-macro-builder = { path = "../verilog-macro-builder/" }
verilator.workspace = true
sv-parser.workspace = true
