name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 1 # since we cache

jobs:
  test_verilog:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Rust Caching
        uses: Swatinem/rust-cache@v2
      - name: Install verilator
        run: make install_verilator
      - name: Test
        run: |
          cd examples/verilog-project
          cargo run --package example-verilog-project --bin tutorial
          cargo run --package example-verilog-project --bin tutorial # rerun
          cargo run --package example-verilog-project --bin dynamic_model_tutorial
          cargo run --package example-verilog-project --bin dpi_tutorial
          cargo run --package example-verilog-project --bin visibility_works
      
  test_spade:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Rust Caching
        uses: Swatinem/rust-cache@v2
      - name: Install verilator
        run: make install_verilator
      - name: Install swim
        run: cargo install --locked --git https://gitlab.com/spade-lang/swim --rev 639c5d88db76ef3454af4feef842c37985ca1943
      - name: Test
        run: cd examples/spade-project && cargo run --package example-spade-project

  test_swim_marlin:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Rust Caching
        uses: Swatinem/rust-cache@v2
      - name: Install verilator
        run: make install_verilator
      - name: Install swim
        run: cargo install --locked --git https://gitlab.com/spade-lang/swim --rev 639c5d88db76ef3454af4feef842c37985ca1943
      - name: Install swim-marlin
        run: cargo install --path tooling/swim-marlin
      - name: Test
        run: |
          mkdir TMP
          cd TMP
          swim init my_swim_project
          swim marlin init
          swim marlin check
          swim marlin add another_test
          swim marlin test
