name: Docs

permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  playground:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - name: Install callouts preprocessor
        run: cargo install --locked --git https://github.com/ToolmanP/rs-mdbook-callouts --rev 83898e352a961fc65044e04c864141c8b5481722
      - name: Build docs
        run: mdbook build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"
      - id: deployment
        uses: actions/deploy-pages@v4
