name: Docs

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  playground:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - name: Install callouts preprocessor
        run: cargo install --locked --git https://github.com/ToolmanP/rs-mdbook-callouts --rev 83898e352a961fc65044e04c864141c8b5481722
      - name: mdbook
        run: mdbook build
